export const PUBLISHING_OFFICE_PROFILE_FETCH = "PUBLISHING_OFFICE_PROFILE_FETCH";
export const PUBLISHING_OFFICE_PROFILE_FETCH_SUCCESS = "PUBLISHING_OFFICE_PROFILE_FETCH_SUCCESS";
export const PUBLISHING_OFFICE_PROFILE_FETCH_FAIL = "PUBLISHING_OFFICE_PROFILE_FETCH_FAIL";
export const PUBLISHING_OFFICE_PROFILE_CHANGE = "PUBLISHING_OFFICE_PROFILE_CHANGE";
export const PUBLISHING_OFFICE_PROFILE_EDIT = "PUBLISHING_OFFICE_PROFILE_EDIT";
export const PUBLISHING_OFFICE_SAVE = "PUBLISHING_OFFICE_SAVE";
export const PUBLISHING_OFFICE_SAVE_SUCCESS = "PUBLISHING_OFFICE_SAVE_SUCCESS";
export const PUBLISHING_OFFICE_SAVE_FAIL = "PUBLISHING_OFFICE_SAVE_FAIL";
