// fetch profile
export const PUBLISHING_OFFICE_PROFILE_FETCH = "PUBLISHING_OFFICE_PROFILE_FETCH";
export const PUBLISHING_OFFICE_PROFILE_FETCH_SUCCESS = "PUBLISHING_OFFICE_PROFILE_FETCH_SUCCESS";
export const PUBLISHING_OFFICE_PROFILE_FETCH_FAIL = "PUBLISHING_OFFICE_PROFILE_FETCH_FAIL";
// handle form change
export const PUBLISHING_OFFICE_PROFILE_CHANGE = "PUBLISHING_OFFICE_PROFILE_CHANGE";
// set edit mode
export const PUBLISHING_OFFICE_PROFILE_EDIT = "PUBLISHING_OFFICE_PROFILE_EDIT";
// save changes
export const PUBLISHING_OFFICE_PROFILE_SAVE = "PUBLISHING_OFFICE_PROFILE_SAVE";
export const PUBLISHING_OFFICE_PROFILE_SAVE_SUCCESS = "PUBLISHING_OFFICE_PROFILE_SAVE_SUCCESS";
export const PUBLISHING_OFFICE_PROFILE_SAVE_FAIL = "PUBLISHING_OFFICE_PROFILE_SAVE_FAIL";
// create new profile
export const PUBLISHING_OFFICE_PROFILE_CREATE = "PUBLISHING_OFFICE_PROFILE_CREATE";
export const PUBLISHING_OFFICE_PROFILE_CREATE_SUCCESS = "PUBLISHING_OFFICE_PROFILE_CREATE_SUCCESS";
export const PUBLISHING_OFFICE_PROFILE_CREATE_FAIL = "PUBLISHING_OFFICE_PROFILE_CREATE_FAIL";
