export const BOOK_PROFILE_FETCH = "BOOK_PROFILE_FETCH";
export const BOOK_PROFILE_FETCH_SUCCESS = "BOOK_PROFILE_FETCH_SUCCESS";
export const BOOK_PROFILE_FETCH_FAIL = "BOOK_PROFILE_FETCH_FAIL";
export const BOOK_PROFILE_EDIT = "BOOK_PROFILE_EDIT";
export const BOOK_PROFILE_EDITING = "BOOK_PROFILE_EDITING";
export const BOOK_PROFILE_EDITING_DONE = "BOOK_PROFILE_EDITING_DONE";
