export const BOOK_LIST_FETCH = "BOOK_LIST_FETCH";
export const BOOK_LIST_FETCH_SUCCESS = "BOOK_LIST_FETCH_SUCCESS";
export const BOOK_LIST_FETCH_FAIL = "BOOK_LIST_FETCH_FAIL";
export const BOOK_PROFILE_DELETE = "BOOK_PROFILE_DELETE";
export const BOOK_PROFILE_DELETE_SUCCESS = "BOOK_PROFILE_DELETE_SUCCESS";
export const BOOK_PROFILE_DELETE_FAIL = "BOOK_PROFILE_DELETE_FAIL";
