# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:9000/api/customer
Content-Type: application/json
Authorization: {{auth_token}}

{
    "name": "name",
    "date_of_birth": "date_of_birth",
    "email": "email@email.com"
}

###

GET http://localhost:9000/api/customer
Accept: application/json
Authorization: {{auth_token}}

###

GET http://localhost:9000/api/customer?scroll=5&limit=2
Accept: application/json
Authorization: {{auth_token}}

###

GET http://localhost:9000/api/customer/10
Accept: application/json

###

PUT http://localhost:9000/api/customer/1
Content-Type: application/json
Authorization: {{auth_token}}

{
    "email": "new@email.com"
}

###

DELETE http://localhost:9000/api/customer/1
Authorization: {{auth_token}}

###
