export const PUBLISHING_OFFICE_LIST_FETCH = "PUBLISHING_OFFICE_LIST_FETCH";
export const PUBLISHING_OFFICE_LIST_FETCH_SUCCESS = "PUBLISHING_OFFICE_LIST_FETCH_SUCCESS";
export const PUBLISHING_OFFICE_LIST_FETCH_FAIL = "PUBLISHING_OFFICE_LIST_FETCH_FAIL";
export const PUBLISHING_OFFICE_LIST_DELETE = "PUBLISHING_OFFICE_LIST_DELETE";
export const PUBLISHING_OFFICE_LIST_DELETE_SUCCESS = "PUBLISHING_OFFICE_LIST_DELETE_SUCCESS";
export const PUBLISHING_OFFICE_LIST_DELETE_FAIL = "PUBLISHING_OFFICE_LIST_DELETE_FAIL";
